function out = x11(varargin)
%X11  Build (or set on a spec) the x11 spec for X11 seasonal adjustment.
%
%   tse.x13.x11('mode', 'mult', 'seasonalma', 's3x9')
%   tse.x13.x11(spec, ...)      sets spec.x11
    [spec, args] = tse.x13.specsplit(varargin{:});
    D = tse.x13.X13default();
    d = struct('appendbcst',D,'appendfcst',D,'final',D,'mode',D,'print',D,'save',D, ...
        'seasonalma',D,'sigmalim',D,'title',D,'trendma',D,'type',D,'calendarsigma',D, ...
        'centerseasonal',D,'keepholiday',D,'print1stpass',D,'sfshort',D,'sigmavec',D, ...
        'trendic',D,'true7term',D);
    d.savelog = 'alldiagnostics';
    o = tse.x13.getopts(d, args);

    if ~tse.x13.isdefault(o.trendma)
        if mod(o.trendma, 2) ~= 1 || o.trendma < 3 || o.trendma > 101
            error('tseries:noMatch', 'trendma must be an odd number between 3 and 101. Received: %d.', o.trendma);
        end
    end
    if ~tse.x13.isdefault(o.sigmavec)
        if tse.x13.isdefault(o.calendarsigma) || ...
                ((ischar(o.calendarsigma) || isstring(o.calendarsigma)) && ~strcmp(char(o.calendarsigma), 'select'))
            error('tseries:noMatch', 'The sigmavec argument can only be specified when calendarsigma=select.');
        end
    end

    o.print = tse.x13.expandall(o.print, {'adjustdiff','adjustfac','adjustmentratio', ...
        'calendar','calendaradjchanges','combholiday','ftestd8','irregular','irrwt', ...
        'movseasrat','origchanges','qstat','replacsi','residualseasf','sachanges','seasadj', ...
        'seasonal','seasonaldiff','tdaytype','trend','trendchanges','unmodsi','unmodsiox', ...
        'x11diag','yrtotals','adjoriginalc','adjoriginald','autosf','extreme','extremeb', ...
        'ftestb1','irregularadjao','irregularb','irregularc','irrwtb','mcdmovavg','modirregular', ...
        'modoriginal','modseasadj','modsic4','modsid4','replacsib4','replacsib9','replacsic9', ...
        'robustsa','seasadjb11','seasadjb6','seasadjc11','seasadjc6','seasadjconst','seasadjd6', ...
        'seasonalb10','seasonalb5','seasonalc10','seasonalc5','seasonald5','sib3','sib8', ...
        'tdadjorig','tdadjorigb','trendadjls','trendb2','trendb7','trendc2','trendc7', ...
        'trendconst','trendd2','trendd7','irregularplot','origwsaplot','ratioplotorig', ...
        'ratioplotsa','seasadjplot','seasonalplot','trendplot'});
    o.save = tse.x13.expandall(o.save, {'adjustdiff','adjustfac','adjustmentratio', ...
        'calendar','calendaradjchanges','combholiday','irregular','irrwt','origchanges', ...
        'replacsi','sachanges','seasadj','seasonal','seasonaldiff','totaladjustment','trend', ...
        'trendchanges','unmodsi','unmodsiox','adjoriginalc','adjoriginald','extreme','extremeb', ...
        'irregularadjao','irregularb','irregularc','irrwtb','mcdmovavg','modirregular', ...
        'modoriginal','modseasadj','modsic4','modsid4','replacsic9','robustsa','seasadjb11', ...
        'seasadjb6','seasadjc11','seasadjc6','seasadjconst','seasadjd6','seasonalb10', ...
        'seasonalb5','seasonalc10','seasonalc5','seasonald5','sib3','sib8','tdadjorig', ...
        'tdadjorigb','trendadjls','trendb2','trendb7','trendc2','trendc7','trendconst', ...
        'trendd2','trendd7','adjustfacpct','calendaradjchangespct','irregularpct', ...
        'origchangespct','sachangespct','seasonalpct','trendchangespct'});

    obj = tse.x13.X13x11();
    obj.appendbcst = o.appendbcst; obj.appendfcst = o.appendfcst; obj.final = o.final;
    obj.mode = o.mode; obj.print = o.print; obj.save = o.save; obj.savelog = o.savelog;
    obj.seasonalma = o.seasonalma; obj.sigmalim = o.sigmalim; obj.title = o.title;
    obj.trendma = o.trendma; obj.type = o.type; obj.calendarsigma = o.calendarsigma;
    obj.centerseasonal = o.centerseasonal; obj.keepholiday = o.keepholiday;
    obj.print1stpass = o.print1stpass; obj.sfshort = o.sfshort; obj.sigmavec = o.sigmavec;
    obj.trendic = o.trendic; obj.true7term = o.true7term;

    out = tse.x13.specfinish(spec, 'x11', obj);
end
