function C = x13consts()
%X13CONSTS  Lookup tables used when classifying and describing X13 outputs.
%
%   Returns a struct with the file-extension classification tables used while
%   parsing X13 output, along with ported metadata from the Julia x13consts.jl
%   implementation:
%
%     output_alt_names
%     output_save_tables
%     output_descriptions
%     output_udg_description
%
%   The values are cached in a persistent variable.
    persistent cached
    if ~isempty(cached)
        C = cached;
        return
    end

    C.series_extensions = { ...
        'rrs','rmx','rsd','ref','trn','fct', ...
        'a1','a2','a3','a4','a10','a18','a19', ...
        'b1','b2','b3','b5','b6','b7','b8','b10','b11','b13','b14','b16','b17','b19','b20', ...
        'c1','c2','c4','c5','c6','c7','c10','c11','c13','c14','c16','c17','c18','c19','c20', ...
        'd1','d2','d4','d5','d6','d7','d8','d9','d12','d10','d11','d13','d16','d18', ...
        'e1','e2','e3','e5','e6','e7','e8','e11','e18', ...
        's10','s11','s12','s13','s14','s16','s18', ...
        'tad','psf','pir','pe5','pe6','pe7','pe8','paf','f1','otl','ftr','ira','fvr', ...
        'p6a','p6r','e6a','e6r','saa','ffc', ...
        'rnd','fts','btr','bct','fch','fce','amh','tre','sae','trr','sar','tal','ycs', ...
        'sfs','chs','tds','ads', ...
        'a2p','a1c','a2t','xrm','a4d','xhl','bxh','xca','xcc', ...
        'yfd','tse','tfd','ssm','sse','sfd','se3','se2','dtr','dsa','dor','cse','ase', ...
        'afd','pss','psi','psc','ltt','cyc', ...
        'td','ao','ls','hol','chl','tc','usr','fsd','fad','mv'};

    C.probably_series_extensions = { ...
        'sas','ais','so','a13','sec','stc','sta','ser','ter','b18','bxc','bcc','a3p','a4p', ...
        'chr','iar','tcr','sfr','che','iae','tce','sfe','sac','ofd','xrc','c9'};

    C.table_extensions = { ...
        'pcf','acf','ac2','itr','spr','sp0','sp1','sp2','str','st0','st1','st2','rts','acm', ...
        'rcm','d8b','oit','rot','xoi','t1s','t2s','s1s','s2s','ttc','tac','gtf','gtc','gaf', ...
        'gac','ftf','ftc','faf','fac','wkf','13'};

    C.kv_list_extensions = {'lks','mdc'};
    C.human_text_extensions = {'spc','gmt','out','sum'};

    C.ordered_month_names = {'jan','feb','mar','apr','may','jun', ...
                             'jul','aug','sep','oct','nov','dec'};

    mq = containers.Map('KeyType', 'char', 'ValueType', 'double');
    for i = 1:12
        mq(C.ordered_month_names{i}) = i;
    end
    C.months_and_quarters = mq;

    C.output_alt_names = local_output_alt_names();
    C.output_save_tables = local_output_save_tables();
    C.output_descriptions = local_output_descriptions();
    C.output_udg_description = local_output_udg_description();

    cached = C;
end

function S = local_output_alt_names()
    specs = local_spec_names();
    S = local_empty_spec_struct(specs);
    lines = [ ...
        "automdl|ach|autochoice"
        "automdl|amd|autochoicemdl"
        "automdl|adt|autodefaulttests"
        "automdl|aft|autofinaltests"
        "automdl|alb|autoljungboxtest"
        "automdl|b5m|bestfivemdl"
        "automdl|hdr|header"
        "automdl|urt|unitroottest"
        "automdl|urm|unitroottestmdl"
        "automdl|adf|autodiff"
        "automdl|mu|mean"
        "check|acf|acf"
        "check|acp|acfplot"
        "check|pcf|pacf"
        "check|pcp|pacfplot"
        "check|ac2|acfsquared"
        "check|ap2|acfsquaredplot"
        "check|nrm|normalitytest"
        "check|dw|durbinwatson"
        "check|frt|friedmantest"
        "check|hst|histogram"
        "check|nrm|normalitytest"
        "check|lbq|ljungboxq"
        "check|bpq|boxpierceq"
        "check|dw|durbinwatson"
        "check|sft|seasonalftest"
        "check|tft|tdftest"
        "estimate|opt|options"
        "estimate|mdl|model"
        "estimate|est|estimates"
        "estimate|afc|averagefcsterr"
        "estimate|lks|lkstats"
        "estimate|itr|iterations"
        "estimate|ite|iterationerrors"
        "estimate|rcm|regcmatrix"
        "estimate|acm|armacmatrix"
        "estimate|lkf|lformulas"
        "estimate|rts|roots"
        "estimate|ref|regressioneffects"
        "estimate|rrs|regressionresiduals"
        "estimate|rsd|residuals"
        "estimate|aic|aic"
        "estimate|acc|aicc"
        "estimate|bic|bic"
        "estimate|hq|hannanquinn"
        "force|saa|seasadjtot"
        "force|rnd|saround"
        "force|e6a|revsachanges"
        "force|e6r|rndsachanges"
        "force|p6a|revsachangespct"
        "force|p6r|rndsachangespct"
        "forecast|ftr|transformed"
        "forecast|fvr|variances"
        "forecast|fct|forecasts"
        "forecast|btr|transformedbcst"
        "forecast|bct|backcasts"
        "history|hdr|header"
        "history|rot|outlierhistory"
        "history|sar|sarevisions"
        "history|sas|sasummary"
        "history|chr|chngrevisions"
        "history|chs|chngsummary"
        "history|iar|indsarevisions"
        "history|ias|indsasummary"
        "history|trr|trendrevisions"
        "history|trs|trendsummary"
        "history|tcr|trendchngrevisions"
        "history|tcs|trendchngsummary"
        "history|sfr|sfrevisions"
        "history|ssm|sfsummary"
        "history|lkh|lkhdhistory"
        "history|fce|fcsterrors"
        "history|amh|armahistory"
        "history|tdh|tdhistory"
        "history|sfh|sfilterhistory"
        "history|sae|saestimates"
        "history|che|chngestimates"
        "history|iae|indsaestimates"
        "history|tre|trendestimates"
        "history|tce|trendchngestimates"
        "history|sfe|sfestimates"
        "history|fch|fcsthistory"
        "history|asa|aveabsrevsa"
        "history|ach|aveabsrevchng"
        "history|iaa|aveabsrevindsa"
        "history|atr|aveabsrevtrend"
        "history|atc|aveabsrevtrendchng"
        "history|asf|aveabsrevsf"
        "history|asp|aveabsrevsfproj"
        "history|afe|avesumsqfcsterr"
        "identify|iac|acf"
        "identify|acp|acfplot"
        "identify|ipc|pacf"
        "identify|pcp|pacfplot"
        "identify|rgc|regcoefficients"
        "outlier|hdr|header"
        "outlier|oit|iterations"
        "outlier|ots|tests"
        "outlier|tls|temporaryls"
        "outlier|fts|finaltests"
        "pickmdl|pmc|pickmdlchoice"
        "pickmdl|hdr|header"
        "pickmdl|umd|usermodels"
        "regression|rmx|regressionmatrix"
        "regression|ats|aictest"
        "regression|otl|outlier"
        "regression|ao|aoutlier"
        "regression|ls|levelshift"
        "regression|so|seasonaloutlier"
        "regression|a13|transitory"
        "regression|tc|temporarychange"
        "regression|td|tradingday"
        "regression|hol|holiday"
        "regression|a10|regseasonal"
        "regression|usr|userdef"
        "regression|cts|chi2test"
        "regression|tdw|dailyweights"
        "seats|s10|seasonal"
        "seats|s13|irregular"
        "seats|s11|seasonaladj"
        "seats|s14|transitory"
        "seats|s16|adjustfac"
        "seats|s18|adjustmentratio"
        "seats|tfd|trendfcstdecomp"
        "seats|sfd|seasonalfcstdecomp"
        "seats|ofd|seriesfcstdecomp"
        "seats|afd|seasonaladjfcstdecomp"
        "seats|yfd|transitoryfcstdecomp"
        "seats|sec|seasadjconst"
        "seats|stc|trendconst"
        "seats|sta|totaladjustment"
        "seats|dor|difforiginal"
        "seats|dsa|diffseasonaladj"
        "seats|dtr|difftrend"
        "seats|ssm|seasonalsum"
        "seats|cyc|cycle"
        "seats|ltt|longtermtrend"
        "seats|mdc|componentmodels"
        "seats|fac|filtersaconc"
        "seats|faf|filtersasym"
        "seats|ftc|filtertrendconc"
        "seats|ftf|filtertrendsym"
        "seats|gac|squaredgainsaconc"
        "seats|gaf|squaredgainsasym"
        "seats|gtc|squaredgaintrendconc"
        "seats|gtf|squaredgaintrendsym"
        "seats|tac|timeshiftsaconc"
        "seats|ttc|timeshifttrendconc"
        "seats|wkf|wkendfilter"
        "seats|pss|seasonalpct"
        "seats|psi|irregularpct"
        "seats|psc|transitorypct"
        "seats|psa|adjustfacpct"
        "seats|smd|seatsmodel"
        "seats|xmd|x13model"
        "seats|nrm|normalitytest"
        "seats|oue|overunderestimation"
        "seats|tse|totalsquarederror"
        "seats|cvr|componentvariance"
        "seats|cee|concurrentesterror"
        "seats|prs|percentreductionse"
        "seats|aad|averageabsdiffannual"
        "seats|ssg|seasonalsignif"
        "series|hdr|header"
        "series|a1|span"
        "series|a1p|seriesplot"
        "series|spc|specfile"
        "series|sav|savefile"
        "series|sp0|specorig"
        "series|mv|missingvaladj"
        "series|a18|calendaradjorig"
        "series|a19|outlieradjorig"
        "series|b1|adjoriginal"
        "series|b1p|adjorigplot"
        "slidingspans|hdr|header"
        "slidingspans|ssf|ssftest"
        "slidingspans|fmn|factormeans"
        "slidingspans|pct|percent"
        "slidingspans|sum|summary"
        "slidingspans|smy|yysummary"
        "slidingspans|fmi|indfactormeans"
        "slidingspans|pci|indpercent"
        "slidingspans|smi|indsummary"
        "slidingspans|pcy|yypercent"
        "slidingspans|sfs|sfspans"
        "slidingspans|chs|chngspans"
        "slidingspans|sas|saspans"
        "slidingspans|ycs|ychngspans"
        "slidingspans|tds|tdspans"
        "slidingspans|pyi|indyypercent"
        "slidingspans|syi|indyysummary"
        "slidingspans|sis|indsfspans"
        "slidingspans|cis|indchngspans"
        "slidingspans|ais|indsaspans"
        "slidingspans|yis|indychngspans"
        "spectrum|sp0|specorig"
        "spectrum|sp1|specsa"
        "spectrum|sp2|specirr"
        "spectrum|s1s|specseatssa"
        "spectrum|s2s|specseatsirr"
        "spectrum|ser|specextresiduals"
        "spectrum|spr|specresidual"
        "spectrum|is0|speccomposite"
        "spectrum|is2|specindirr"
        "spectrum|is1|specindsa"
        "spectrum|tpk|tukeypeaks"
        "spectrum|st0|tukeyspecorig"
        "spectrum|st1|tukeyspecsa"
        "spectrum|st2|tukeyspecirr"
        "spectrum|st1|tukeyspecseatssa"
        "spectrum|st2|tukeyspecseatsirr"
        "spectrum|ter|tukeyspecextresiduals"
        "spectrum|str|tukeyspecresidual"
        "spectrum|it0|tukeyspeccomposite"
        "spectrum|it2|tukeyspecindirr"
        "spectrum|it1|tukeyspecindsa"
        "spectrum|dpk|dirpeaks"
        "spectrum|dqs|dirqs"
        "spectrum|dtp|dirtukeypeaks"
        "spectrum|ipk|indpeaks"
        "spectrum|iqs|indqs"
        "spectrum|itp|indtukeypeaks"
        "spectrum|spk|peaks"
        "spectrum|stp|tukeypeaks"
        "spectrum|a1|original"
        "spectrum|a19|outlieradjoriginal"
        "spectrum|b1|adjoriginal"
        "spectrum|e1|modoriginal"
        "transform|tac|aictransform"
        "transform|a1c|seriesconstant"
        "transform|acp|seriesconstantplot"
        "transform|a2|prior"
        "transform|a2p|permprior"
        "transform|a2t|tempprior"
        "transform|a3|prioradjusted"
        "transform|a3p|permprioradjusted"
        "transform|a4d|prioradjustedptd"
        "transform|a4p|permprioradjustedptd"
        "transform|trn|transformed"
        "x11|fad|adjustdiff"
        "x11|d16|adjustfac"
        "x11|e18|adjustmentratio"
        "x11|d18|calendar"
        "x11|e8|calendaradjchanges"
        "x11|chl|combholiday"
        "x11|d8f|ftestd8"
        "x11|d13|irregular"
        "x11|c17|irrwt"
        "x11|d9a|movseasrat"
        "x11|e5|origchanges"
        "x11|f3|qstat"
        "x11|d9|replacsi"
        "x11|rsf|residualseasf"
        "x11|e6|sachanges"
        "x11|d11|seasadj"
        "x11|d10|seasonal"
        "x11|fsd|seasonaldiff"
        "x11|tdy|tdaytype"
        "x11|tad|totaladjustment"
        "x11|d12|trend"
        "x11|e7|trendchanges"
        "x11|d8|unmodsi"
        "x11|d8b|unmodsiox"
        "x11|f2|x11diag"
        "x11|e4|yrtotals"
        "x11|c1|adjoriginalc"
        "x11|d1|adjoriginald"
        "x11|asf|autosf"
        "x11|c20|extreme"
        "x11|b20|extremeb"
        "x11|b1f|ftestb1"
        "x11|ira|irregularadjao"
        "x11|b13|irregularb"
        "x11|c13|irregularc"
        "x11|b17|irrwtb"
        "x11|f1|mcdmovavg"
        "x11|e3|modirregular"
        "x11|e1|modoriginal"
        "x11|e2|modseasadj"
        "x11|c4|modsic4"
        "x11|d4|modsid4"
        "x11|b4|replacsib4"
        "x11|b9|replacsib9"
        "x11|c9|replacsic9"
        "x11|e11|robustsa"
        "x11|b11|seasadjb11"
        "x11|b6|seasadjb6"
        "x11|c11|seasadjc11"
        "x11|c6|seasadjc6"
        "x11|sac|seasadjconst"
        "x11|d6|seasadjd6"
        "x11|b10|seasonalb10"
        "x11|b5|seasonalb5"
        "x11|c10|seasonalc10"
        "x11|c5|seasonalc5"
        "x11|d5|seasonald5"
        "x11|b3|sib3"
        "x11|b8|sib8"
        "x11|c19|tdadjorig"
        "x11|b19|tdadjorigb"
        "x11|tal|trendadjls"
        "x11|b2|trendb2"
        "x11|b7|trendb7"
        "x11|c2|trendc2"
        "x11|c7|trendc7"
        "x11|tac|trendconst"
        "x11|d2|trendd2"
        "x11|d7|trendd7"
        "x11|irregularplot|irregularplot"
        "x11|origwsaplot|origwsaplot"
        "x11|ratioplotorig|ratioplotorig"
        "x11|ratioplotsa|ratioplotsa"
        "x11|seasadjplot|seasadjplot"
        "x11|seasonalplot|seasonalplot"
        "x11|trendplot|trendplot"
        "x11|paf|adjustfacpct"
        "x11|pe8|calendaradjchangespct"
        "x11|pir|irregularpct"
        "x11|pe5|origchangespct"
        "x11|pe6|sachangespct"
        "x11|psf|seasonalpct"
        "x11|pe7|trendchangespct"
        "x11|fb1|fstableb1"
        "x11|fd8|fstabled8"
        "x11|icr|icratio"
        "x11|ids|idseasonal"
        "x11|m1|m1"
        "x11|m10|m10"
        "x11|m11|m11"
        "x11|m2|m2"
        "x11|m3|m3"
        "x11|m4|m4"
        "x11|m5|m5"
        "x11|m6|m6"
        "x11|m7|m7"
        "x11|m8|m8"
        "x11|m9|m9"
        "x11|msf|movingseasf"
        "x11|msr|movingseasratio"
        "x11|q|q"
        "x11|q2|q2"
        "x11regression|a4|priortd"
        "x11regression|c14|extremeval"
        "x11regression|c15|x11reg"
        "x11regression|c16|tradingday"
        "x11regression|c18|combtradingday"
        "x11regression|xhl|holiday"
        "x11regression|xca|calendar"
        "x11regression|xcc|combcalendar"
        "x11regression|xoh|outlierhdr"
        "x11regression|xat|xaictest"
        "x11regression|b14|extremevalb"
        "x11regression|b15|x11regb"
        "x11regression|b16|tradingdayb"
        "x11regression|b18|combtradingdayb"
        "x11regression|bxh|holidayb"
        "x11regression|bxc|calendarb"
        "x11regression|bcc|combcalendarb"
        "x11regression|xoi|outlieriter"
        "x11regression|xot|outliertests"
        "x11regression|xrm|xregressionmatrix"
        "x11regression|xrc|xregressioncmatrix"
    ];
    S = local_fill_spec_struct(S, lines);
end

function S = local_output_save_tables()
    specs = local_spec_names();
    S = local_empty_code_struct(specs);
    S.check = local_codes(["acf","pcf","ac2"]);
    S.estimate = local_codes(["mdl","est","lks","itr","rcm","acm","rts","ref","rrs","rsd"]);
    S.force = local_codes(["saa","rnd","e6a","e6r","p6a","p6r"]);
    S.forecast = local_codes(["ftr","fvr","fct","btr","bct"]);
    S.history = local_codes(["rot","sar","chr","iar","trr","tcr","sfr","lkh","fce","amh","tdh","sfh","sae","che","iae","tre","tce","sfe","fch"]);
    S.identify = local_codes(["iac","ipc"]);
    S.outlier = local_codes(["oit","fts"]);
    S.regression = local_codes(["rmx","otl","ao","ls","so","a13","tc","td","hol","a10","usr"]);
    S.seats = local_codes(["s11","dsa","ttc","sec","tac","ftf","ofd","afd","s10","s16","dor","s18","yfd","faf","gaf","stc","wkf","tfd","s13","s14","sta","dtr","gac","gtc","gtf","cyc","ssm","mdc","ftc","sfd","ltt","fac","pss","psi","psc","psa"]);
    S.series = local_codes(["a1","sp0","mva","a18","a19","b1"]);
    S.slidingspans = local_codes(["smy","sfs","chs","sas","ycs","tds","sis","cis","ais","yis"]);
    S.spectrum = local_codes(["is1","sp2","sp0","s1s","st2","is2","it0","s2s","it1","sp1","str","ser","ter","st0","is0","it2","spr","st1"]);
    S.transform = local_codes(["a2","a2t","a4d","a3","trn","a4p","a2p","a3p","a1c"]);
    S.x11 = local_codes(["d4","tad","d8b","e1","d6","b5","d9","d2","d1","tac","c2","b20","e7","c9","b17","c7","c13","b10","f1","c11","e2","d12","c19","e11","c6","b3","tal","e5","b7","b19","c4","ira","e3","fsd","b2","e18","d10","b11","c1","c17","e6","d11","c10","d5","b8","d16","fad","b6","d8","d18","d13","sac","d7","e8","chl","c5","b13","c20","paf","pe8","pir","pe5","pe6","psf","pe7"]);
    S.x11regression = local_codes(["a4","c14","c16","c18","xhl","xca","xcc","b14","b16","b18","bxh","bxc","bcc","xoi","xrm","xrc"]);
end

function S = local_output_descriptions()
    specs = local_spec_names();
    S = local_empty_spec_struct(specs);
    lines = [ ...
        "automdl|ach|model choice of automatic model procedure"
        "automdl|amd|summary output for models estimated during choice of ARMA model orders"
        "automdl|adt|tests performed on the default model (usually the airline model) of the automatic model identification procedure"
        "automdl|aft|final tests performed on the model identified by automdl"
        "automdl|alb|check of the residual Ljung-Box statistic"
        "automdl|b5m|summary of best five models found during choice of ARMA model orders"
        "automdl|hdr|header for the automatic modeling output"
        "automdl|urt|choice of differencing"
        "automdl|urm|summary output for models estimated during difference order identification"
        "automdl|adf|choice of differencing by automatic model identification procedure"
        "automdl|mu|choice regarding use of constant term with automatically identified model"
        "check|acf|autocorrelation function of residuals with standard errors, and Ljung-Box Q-statistics computed through each lag"
        "check|acp|plot of residual autocorrelation function with plus/minus 2 standard error limits"
        "check|pcf|partial autocorrelation function of residuals with standard errors"
        "check|pcp|plot of residual partial autocorrelation function with plus/minus 2 standard error limits"
        "check|ac2|autocorrelation function of squared residuals with standard errors, and Ljung-Box Q-statistics computed through each lag"
        "check|ap2|plot of squared residual autocorrelation function with plus/minus 2 standard error limits"
        "check|nrm|Geary's a and Kurtosis statistical tests for the normality of the model residuals, as well as a test for skewness of the residuals."
        "check|dw|Durbin-Watson statistic for model residuals"
        "check|frt|Friedman non-parametric test for residual seasonality"
        "check|hst|histogram of standardized residuals and the following summary statistics of the residuals: minimum, maximum, median, standard deviation, and robust estimate of residual standard deviation (1.48 times the median absolute deviation)"
        "check|nrm|Test results from the normality tests on the regARIMA model residuals (Kurtosis, skewness and Geary's a statistics)"
        "check|lbq|Significant lags for the Ljung-Box Q statistic"
        "check|bpq|Significant lags for the Box-Pierce Q statistic"
        "check|dw|Durbin-Watson statistic for regARIMA model residuals"
        "check|sft|Model-based f-statistic for seasonality from Lytras, Feldpausch, and Bell (2007)"
        "check|tft|Model-based f-statistic for trading day from Pang and Monsell (2016)"
        "estimate|opt|header for the estimation options"
        "estimate|mdl|if used with the print argument, this controls printing of a short description of the model; if used with the save argument, this creates a file containing regression and arima specs corresponding to the model, with the estimation results used to specify initial values for the ARMA parameters"
        "estimate|est|regression and ARMA parameter estimates, with standard errors"
        "estimate|afc|average magnitude of forecast errors over each of the last three years of data."
        "estimate|lks|log-likelihood at final parameter estimates and, if exact equals arma is used (default option), corresponding model selection criteria (AIC, AICC, Hannan-Quinn, BIC)"
        "estimate|itr|detailed output for estimation iterations, including log-likelihood values and parameters, and counts of function evaluations and iterations"
        "estimate|ite|error messages for estimation iterations, including failure to converge"
        "estimate|rcm|correlation matrix of regression parameter estimates if used with the print argument; covariance matrix of same if used with the save argument"
        "estimate|acm|correlation matrix of ARMA parameter estimates if used with the print argument; covariance matrix of same if used with the save argument"
        "estimate|lkf|formulas for computing the log-likelihood and model selection criteria"
        "estimate|rts|roots of the autoregressive and moving average operators in the estimated model"
        "estimate|ref|X beta hat, matrix of regression variables multiplied by the vector of estimated regression coefficients"
        "estimate|rrs|residuals from regression effects"
        "estimate|rsd|model residuals with associated dates or observation numbers"
        "estimate|aic|Akaike's Information Criterion (AIC)"
        "estimate|acc|Akaike's Information Criterion (AIC) adjusted for the length of the series"
        "estimate|bic|Baysean Information Criterion (BIC)"
        "estimate|hq|Hannan-Quinn Information Criterion"
        "force|saa|final seasonally adjusted series with constrained yearly totals (if type equals regress or type equals denton)"
        "force|rnd|rounded final seasonally adjusted series (if round equals yes) or the rounded final seasonally adjusted series with constrained yearly totals (if type equals regress or type equals denton)"
        "force|e6a|percent changes (differences) in seasonally adjusted series with revised yearly totals"
        "force|e6r|percent changes (differences) in rounded seasonally adjusted series"
        "force|p6a|percent changes in seasonally adjusted series with forced yearly totals"
        "force|p6r|percent changes in rounded seasonally adjusted series"
        "forecast|ftr|forecasts on the transformed scale, with corresponding forecast standard errors"
        "forecast|fvr|forecast error variances on the transformed scale, showing the contributions of the error assuming the model is completely known (stochastic variance) and the error due to estimating any regression parameters (error in estimating AR and MA parameters is ignored)"
        "forecast|fct|point forecasts on the original scale, along with upper and lower prediction interval limits"
        "forecast|btr|backcasts on the transformed scale, with corresponding forecast standard errors"
        "forecast|bct|point backcasts on the original scale, along with upper and lower prediction interval limits"
        "history|hdr|header for history analysis"
        "history|rot|record of outliers removed and kept for the revisions history (printed only if automatic outlier identification is used)"
        "history|sar|revision from concurrent to most recent estimate of the seasonally adjusted data"
        "history|sas|summary statistics for seasonal adjustment revisions"
        "history|chr|revision from concurrent to most recent estimate of the month-to-month (or quarter-to-quarter) changes in the seasonally adjusted data"
        "history|chs|summary statistics for revisions in the month-to-month (or quarter-to-quarter) changes in the seasonally adjusted data"
        "history|iar|revision from concurrent to most recent estimate of the indirect seasonally adjusted series"
        "history|ias|summary statistics for indirect seasonal adjustment revisions"
        "history|trr|revision from concurrent to most recent estimate of the trend component"
        "history|trs|summary statistics for trend component revisions"
        "history|tcr|revision from concurrent to most recent estimate of the month-to-month (or quarter-to-quarter) changes in the trend component"
        "history|tcs|summary statistics for revisions in the month-to-month (or quarter-to-quarter) changes in the trend component"
        "history|sfr|revision from concurrent to most recent estimate of the seasonal factor, as well as projected seasonal factors."
        "history|ssm|summary statistics for seasonal factor revisions"
        "history|lkh|history of AICC and likelihood values"
        "history|fce|revision history of the accumulated sum of squared forecast errors"
        "history|amh|history of estimated AR and MA coefficients from the reg-ARIMA model"
        "history|tdh|history of estimated trading day regression coefficients from the regARIMA model"
        "history|sfh|record of seasonal filter selection for each observation in the revisions history (printed only if automatic seasonal filter selection is used)"
        "history|sae|concurrent and most recent estimate of the seasonally adjusted data"
        "history|che|concurrent and most recent estimate of the month-tomonth (or quarter-to-quarter) changes in the seasonally adjusted data"
        "history|iae|concurrent and most recent estimate of the indirect seasonally adjusted data"
        "history|tre|concurrent and most recent estimate of the trend component"
        "history|tce|concurrent and most recent estimate of the month-tomonth (or quarter-to-quarter) changes in the trend component"
        "history|sfe|concurrent and most recent estimate of the seasonal factors and projected seasonal factors"
        "history|fch|listing of the forecast and forecast errors used to generate accumulated sum of squared forecast errors"
        "history|asa|average absolute revision of the seasonally adjusted series"
        "history|ach|average absolute revision of the month-to-month (or quarter-to-quarter) changes in the seasonally adjusted data"
        "history|iaa|average absolute revision of the indirect seasonally adjusted series"
        "history|atr|average absolute revision of the final trend component"
        "history|atc|average absolute revision of the month-to-month (or quarter-to-quarter) changes in the trend component"
        "history|asf|average absolute revision of the final seasonal factors"
        "history|asp|average absolute revision of the projected seasonal factors"
        "history|afe|average sum of squared forecast error for each forecast lag"
        "identify|iac|sample autocorrelation function(s), with standard errors and Ljung-Box Q-statistics for each lag"
        "identify|acp|line printer plot of sample autocorrelation function(s) with plus/minus 2 standard error limits shown on the plot"
        "identify|ipc|sample partial autocorrelation function(s) with standard errors for each lag"
        "identify|pcp|line printer plot of sample partial autocorrelation function(s) with plus/minus 2 standard error limits shown on the plot"
        "identify|rgc|Regression coefficients removed from the transformed series before ACFs and PACFs were generated."
        "outlier|hdr|options specified for outlier detection including critical value, outlier span, and types of outliers searched for"
        "outlier|oit|detailed results for each iteration of outlier detection including outliers detected, outliers deleted, model parameter estimates, and robust and non-robust estimates of the residual standard deviation"
        "outlier|ots|t-statistics for every time point and outlier type on each outlier detection iteration"
        "outlier|tls|summary of t-statistics for temporary level shift tests"
        "outlier|fts|t-statistics for every time point and outlier type generated during the final outlier detection iteration"
        "pickmdl|pmc|model choice of pickmdl automatic model selection procedure"
        "pickmdl|hdr|header for the pickmdl output"
        "pickmdl|umd|output for each model used in the pickmdl automatic model selection procedure"
        "regression|rmx|values of regression variables with associated dates"
        "regression|ats|output from AIC-based test(s) for trading day, Easter, and user-defined regression variables"
        "regression|otl|combined regARIMA outlier factors (table A8)"
        "regression|ao|regARIMA additive (or point) outlier factors (table A8.AO)"
        "regression|ls|regARIMA level change, temporary level change and ramp outlier factors (table A8.LS)"
        "regression|so|regARIMA seasonal outlier factors (table A8.SO)"
        "regression|a13|regARIMA transitory component factors from user-defined regressors (table A13)"
        "regression|tc|regARIMA temporary change outlier factors (table A8.TC)"
        "regression|td|regARIMA trading day factors (table A6)"
        "regression|hol|regARIMA holiday factors (table A7)"
        "regression|a10|regARIMA user-defined seasonal factors (table A10)"
        "regression|usr|factors from user-defined regression variables (table A9)"
        "regression|cts|output from chi-squared based test for groups of user-defined regression variables"
        "regression|tdw|Daily weights from trading day regressors, normalized to sum to seven"
        "seats|s10|final SEATS seasonal component"
        "seats|s13|final SEATS irregular component"
        "seats|s11|final SEATS seasonal adjustment component"
        "seats|s14|final SEATS transitory component"
        "seats|s16|final SEATS combined adjustment factors"
        "seats|s18|final SEATS adjustment ratio"
        "seats|tfd|forecast of the trend component"
        "seats|sfd|forecast of the seasonal component"
        "seats|ofd|forecast of the series component"
        "seats|afd|forecast of the final SEATS seasonal adjustment"
        "seats|yfd|forecast of the transitory component"
        "seats|sec|final SEATS seasonal adjustment with constant term included"
        "seats|stc|final SEATS trend component with constant term included"
        "seats|sta|total adjustment factors for SEATS seasonal adjustment"
        "seats|dor|fully differenced transformed original series"
        "seats|dsa|fully differenced transformed SEATS seasonal adjustment"
        "seats|dtr|fully differenced transformed SEATS trend"
        "seats|ssm|seasonal-period-length sums of final SEATS seasonal component"
        "seats|cyc|cycle component"
        "seats|ltt|long term trend"
        "seats|mdc|models for the components"
        "seats|fac|concurrent finite seasonal adjustment filter"
        "seats|faf|symmetric finite seasonal adjustment filter"
        "seats|ftc|concurrent finite trend filter"
        "seats|ftf|symmetric finite trend filter"
        "seats|gac|squared gain for finite concurrent seasonal adjustment filter"
        "seats|gaf|squared gain for finite symmetric seasonal adjustment filter"
        "seats|gtc|squared gain for finite concurrent trend filter"
        "seats|gtf|squared gain for finite symmetric trend filter"
        "seats|tac|time shift for finite concurrent seasonal adjustment filter"
        "seats|ttc|time shift for finite concurrent trend filter"
        "seats|wkf|end filters of the semi-infinite Wiener-Kolmogorov filter"
        "seats|pss|final seasonal factors, expressed as percentages if appropriate"
        "seats|psi|final irregular component, expressed as percentages if appropriate"
        "seats|psc|final transitory component, expressed as percentages if appropriate"
        "seats|psa|combined adjustment factors, expressed as percentages if appropriate"
        "seats|smd|Model used by the SEATS module for signal extraction"
        "seats|xmd|Model submitted to the SEATS module"
        "seats|nrm|Normality test"
        "seats|oue|Over-under estimation diagnostics"
        "seats|tse|Total mean squared error"
        "seats|cvr|Component variances"
        "seats|cee|Concurrent estimation error"
        "seats|prs|Percent reduction standard error"
        "seats|aad|Annual Average absolute difference"
        "seats|ssg|Test for seasonal significance"
        "series|hdr|summary of options selected for this run of X-13-ARIMA-SEATS"
        "series|a1|time series data, with associated dates (if the span argument is present, data are printed and or saved only for the specified span)"
        "series|a1p|plot of the original series"
        "series|spc|contents of input specification file used for this run"
        "series|sav|list of files to be produced by the X-13-ARIMA-SEATS run"
        "series|sp0|spectral plot of the first-differenced original series"
        "series|mva|original series with missing values replaced by reg-ARIMA estimates"
        "series|a18|original series adjusted for regARIMA calendar effects"
        "series|a19|original series adjusted for regARIMA outliers"
        "series|b1|original series, adjusted for prior effects and forecast extended"
        "series|b1p|plot of the prior adjusted original series augmented by prior-adjusted forecasts (if specified); if no prior factors or forecasts are used, the original series is plotted"
        "slidingspans|hdr|header text for the sliding spans analysis"
        "slidingspans|ssf|F-tests for stable and moving seasonality estimated over each of the sliding spans"
        "slidingspans|fmn|range analysis for each of the sliding spans"
        "slidingspans|pct|table showing the percent of observations flagged as unstable for the seasonal and or trading day factors, final seasonally adjusted series (if necessary), and the month-to-month (or quarter-toquarter) changes"
        "slidingspans|sum|tables, histograms and hinge values summarizing the percentage of observations flagged for unstable seasonal and or trading day factors, final seasonally adjusted series (if necessary), and month-tomonth (or quarter-to-quarter) changes"
        "slidingspans|smy|additional tables, histograms and hinge values summarizing the percentage of observations flagged for the year-to-year changes"
        "slidingspans|fmi|range analysis for the implicit adjustment factors of the indirectly seasonally adjusted series"
        "slidingspans|pci|tables of the percent of observations flagged as unstable for the seasonal factors and month-tomonth (or quarter-to-quarter) changes of the indirect seasonal adjustment"
        "slidingspans|smi|tables, histograms and hinge values summarizing the percentage of observations flagged for unstable seasonal factors, month-to-month (or quarter-toquarter) and year-to-year changes for the indirect adjustment"
        "slidingspans|pcy|additional entry for the percent of observations flagged as unstable for the year-to-year changes"
        "slidingspans|sfs|seasonal factors from all sliding spans"
        "slidingspans|chs|month-to-month (or quarter-to-quarter) changes from all sliding spans"
        "slidingspans|sas|seasonally adjusted series from all sliding spans"
        "slidingspans|ycs|year-to-year changes from all sliding spans"
        "slidingspans|tds|trading day factors from all sliding spans"
        "slidingspans|pyi|additonal entry for the percent of observations flagged as unstable for the year-to-year (or quarter-to-quarter) changes of the indirect seasonal adjustment"
        "slidingspans|syi|additional tables, histograms and hinge values summarizing the percentage of observations flagged for the year-to-year changes of the indirect seasonal adjustment"
        "slidingspans|sis|indirect seasonal factors from all sliding spans"
        "slidingspans|cis|indirect month-to-month (or quarter-to-quarter) changes from all sliding spans"
        "slidingspans|ais|indirect seasonally adjusted series from all sliding spans"
        "slidingspans|yis|indirect year-to-year changes from all sliding spans"
        "spectrum|qch|QS diagnostic to detect seasonality in quarterly version of a monthly series"
        "spectrum|qs|QS diagnostic to detect seasonality"
        "spectrum|sp0|spectral plot of the first-differenced original series"
        "spectrum|sp1|spectral plot of differenced, X-11 seasonally adjusted series (or of the logged seasonally adjusted series if mode equals logadd or mode equals mult)"
        "spectrum|sp2|spectral plot of outlier-modified X-11 irregular series"
        "spectrum|s1s|spectrum of the differenced final SEATS seasonal adjustment"
        "spectrum|s2s|spectrum of the final SEATS irregular"
        "spectrum|ser|spectrum of the extended residuals"
        "spectrum|spr|spectral plot of the regARIMA model residuals"
        "spectrum|is0|spectral plot of first-differenced aggregate series"
        "spectrum|is2|spectral plot of the first-differenced indirect seasonally adjusted series"
        "spectrum|is1|spectral plot of outlier-modified irregular series from the indirect seasonal adjustment"
        "spectrum|tpk|Peak probability of Tukey spectrum"
        "spectrum|st0|Tukey spectrum of the first-differenced original series"
        "spectrum|st1|Tukey spectrum of the differenced, X-11 seasonally adjusted series (or of the logged seasonally adjusted series if mode equals logadd or mode equals mult)"
        "spectrum|st2|Tukey spectrum of the outlier-modified X-11 irregular series"
        "spectrum|st1|Tukey spectrum of the differenced final SEATS seasonal adjustment"
        "spectrum|st2|Tukey spectrum of the final SEATS irregular"
        "spectrum|ter|Tukey spectrum of the extended residuals"
        "spectrum|str|Tukey spectrum of the regARIMA model residuals"
        "spectrum|it0|Tukey spectrum of the first-differenced aggregate series"
        "spectrum|it2|Tukey spectrum of the first-differenced indirect seasonally adjusted series"
        "spectrum|it1|Tukey spectrum of the outlier-modified irregular series from the indirect seasonal adjustment"
        "spectrum|dpk|Visually significant peaks in spectra for direct seasonal adjustment"
        "spectrum|dqs|QS diagnostic to detect seasonality, direct seasonal adjustment"
        "spectrum|dtp|Peak probabilities for Tukey spectra for direct seasonal adjustment"
        "spectrum|ipk|Visually significant peaks in spectra for indirect seasonal adjustment"
        "spectrum|iqs|QS diagnostic to detect seasonality, indirect seasonal adjustment"
        "spectrum|itp|Peak probabilities for Tukey spectra for inddirect seasonal adjustment"
        "spectrum|spk|Visually significant peaks in spectra"
        "spectrum|stp|Significant peaks of Tukey spectrum"
        "spectrum|a1|original series"
        "spectrum|a19|original series, adjusted for regARIMA outliers"
        "spectrum|b1|original series, adjusted for user specified and reg-"
        "spectrum|e1|original series modified for extremes"
        "transform|tac|output from AIC-based test(s) for transformation"
        "transform|a1c|original series with value from the constant argument added to the series"
        "transform|acp|plot of original series with value from the constant argument added to the series"
        "transform|a2|prior-adjustment factors, with associated dates"
        "transform|a2p|permanent prior-adjustment factors, with associated dates"
        "transform|a2t|temporary prior-adjustment factors, with associated dates"
        "transform|a3|prior-adjusted series, with associated dates"
        "transform|a3p|prior-adjusted series using only permanent prior factors, with associated dates"
        "transform|a4d|prior-adjusted series (including prior trading day adjustments), with associated dates"
        "transform|a4p|prior-adjusted series using only permanent prior factors and prior trading day adjustments, with associated dates"
        "transform|trn|prior-adjusted and transformed data, with associated dates"
        "x11|fad|final adjustment difference (only for pseudo-additive seasonal adjustment)"
        "x11|d16|combined seasonal and trading day factors"
        "x11|e18|final adjustment ratios (original series / seasonally adjusted series)"
        "x11|d18|combined holiday and trading day factors"
        "x11|e8|percent changes (differences) in original series adjusted for calendar effects"
        "x11|chl|combined holiday prior adjustment factors, A16 table"
        "x11|d8f|F-tests for stable and moving seasonality, D8"
        "x11|d13|final irregular component"
        "x11|c17|final weights for the irregular component"
        "x11|d9a|moving seasonality ratios for each period"
        "x11|e5|percent changes (differences) in original series"
        "x11|f3|quality control statistics"
        "x11|d9|final replacement values for extreme SI-ratios (differences), D iteration"
        "x11|rsf|F-test for residual seasonality"
        "x11|e6|percent changes (differences) in seasonally adjusted series"
        "x11|d11|final seasonally adjusted series"
        "x11|d10|final seasonal factors"
        "x11|fsd|final seasonal difference (only for pseudo-additive seasonal adjustment)"
        "x11|tdy|trading day factors printed by type of month"
        "x11|tad|total adjustment factors (only printed out if the original series contains values that are less than or equal to 0)"
        "x11|d12|final trend-cycle"
        "x11|e7|percent changes (differences) in final trend component series"
        "x11|d8|final unmodified SI-ratios (differences)"
        "x11|d8b|final unmodified SI-ratios, with labels for outliers and extreme values"
        "x11|f2|summary of seasonal adjustment diagnostics"
        "x11|e4|ratio of yearly totals of original and seasonally adjusted series"
        "x11|c1|original series modified for outliers, trading day and prior factors, C iteration"
        "x11|d1|original series modified for outliers, trading day and prior factors, D iteration"
        "x11|asf|automatic seasonal factor selection"
        "x11|c20|extreme values, C iteration"
        "x11|b20|extreme values, B iteration"
        "x11|b1f|F-test for stable seasonality, B1 table"
        "x11|ira|final irregular component adjusted for point outliers"
        "x11|b13|irregular component, B iteration"
        "x11|c13|irregular component, C iteration"
        "x11|b17|preliminary weights for the irregular component"
        "x11|f1|MCD moving average of the final seasonally adjusted series"
        "x11|e3|irregular component modified for zero-weighted extreme values"
        "x11|e1|original series modified for zero-weighted extreme values"
        "x11|e2|seasonally adjusted series modified for zero-weighted extreme values"
        "x11|c4|modified SI-ratios (differences), C iteration"
        "x11|d4|modified SI-ratios (differences), D iteration"
        "x11|b4|preliminary replacement values for extreme SI-ratios (differences), B iteration"
        "x11|b9|replacement values for extreme SI-ratios (differences), B iteration"
        "x11|c9|modified SI-ratios (differences), C iteration"
        "x11|e11|robust final seasonally adjusted series"
        "x11|b11|seasonally adjusted series, B iteration"
        "x11|b6|preliminary seasonally adjusted series, B iteration"
        "x11|c11|seasonally adjusted series, C iteration"
        "x11|c6|preliminary seasonally adjusted series, C iteration"
        "x11|sac|final seasonally adjusted series with constant from transform spec included"
        "x11|d6|preliminary seasonally adjusted series, D iteration"
        "x11|b10|seasonal factors, B iteration"
        "x11|b5|preliminary seasonal factors, B iteration"
        "x11|c10|preliminary seasonal factors, C iteration"
        "x11|c5|preliminary seasonal factors, C iteration"
        "x11|d5|preliminary seasonal factors, D iteration"
        "x11|b3|preliminary unmodified SI-ratios (differences)"
        "x11|b8|unmodified SI-ratios (differences)"
        "x11|c19|original series adjusted for final trading day"
        "x11|b19|original series adjusted for preliminary trading day"
        "x11|tal|final trend-cycle adjusted for level shift outliers"
        "x11|b2|preliminary trend-cycle, B iteration"
        "x11|b7|preliminary trend-cycle, B iteration"
        "x11|c2|preliminary trend-cycle, C iteration"
        "x11|c7|preliminary trend-cycle, C iteration"
        "x11|tac|final trend component with constant from transform spec included"
        "x11|d2|preliminary trend-cycle, D iteration"
        "x11|d7|preliminary trend-cycle, D iteration"
        "x11|irregularplot|plot of the final irregular component"
        "x11|origwsaplot|plot of the original series with the final seasonally adjusted series"
        "x11|ratioplotorig|month-to-month (or quarter-to-quarter) ratio plots of the original series"
        "x11|ratioplotsa|month-to-month (or quarter-to-quarter) ratio plots of the seasonally adjusted series"
        "x11|seasadjplot|plot of the final seasonally adjusted series"
        "x11|seasonalplot|seasonal factor plots, grouped by month or quarter"
        "x11|trendplot|plot of the final trend-cycle"
        "x11|paf|combined adjustment factors, expressed as percentages if appropriate"
        "x11|pe8|percent changes in original series adjusted for calendar factors"
        "x11|pir|final irregular component, expressed as percentages if appropriate"
        "x11|pe5|percent changes in the original series"
        "x11|pe6|percent changes in seasonally adjusted series"
        "x11|psf|final seasonal factors, expressed as percentages if appropriate"
        "x11|pe7|percent changes in final trend cycle"
        "x11|fb1|F-test for stable seasonality, performed on the original series"
        "x11|fd8|F-test for stable seasonality, performed on the final SI-ratios"
        "x11|icr|I over C ratio"
        "x11|ids|Identifiable seasonality test result"
        "x11|m1|M1 Quality Control Statistic"
        "x11|m10|M10 Quality Control Statistic"
        "x11|m11|M11 Quality Control Statistic"
        "x11|m2|M2 Quality Control Statistic"
        "x11|m3|M3 Quality Control Statistic"
        "x11|m4|M4 Quality Control Statistic"
        "x11|m5|M5 Quality Control Statistic"
        "x11|m6|M6 Quality Control Statistic"
        "x11|m7|M7 Quality Control Statistic"
        "x11|m8|M8 Quality Control Statistic"
        "x11|m9|M9 Quality Control Statistic"
        "x11|msf|F-test for moving seasonality"
        "x11|msr|Moving seasonality ratio"
        "x11|q|Overall index of the quality of the seasonal adjustment"
        "x11|q2|Q statistic computed without the M2 Quality Control statistic"
        "x11regression|a4|prior trading day weights and factors"
        "x11regression|c14|irregulars excluded from the irregular regression, C iteration"
        "x11regression|c15|final irregular regression coefficients and diagnostics"
        "x11regression|c16|final trading day factors and weights"
        "x11regression|c18|final trading day factors from combined daily weights"
        "x11regression|xhl|final holiday factors"
        "x11regression|xca|final calendar factors (trading day and holiday)"
        "x11regression|xcc|final calendar factors from combined daily weights"
        "x11regression|xoh|options specified for outlier detection including critical value and outlier span"
        "x11regression|xat|output from AIC-based tests for trading day and holiday"
        "x11regression|b14|irregulars excluded from the irregular regression, B iteration"
        "x11regression|b15|preliminary irregular regression coefficients and diagnostics"
        "x11regression|b16|preliminary trading day factors and weights"
        "x11regression|b18|preliminary trading day factors from combined daily weights"
        "x11regression|bxh|preliminary holiday factors"
        "x11regression|bxc|preliminary calendar factors"
        "x11regression|bcc|preliminary calendar factors from combined daily weights"
        "x11regression|xoi|detailed results for each iteration of outlier detection including outliers detected, outliers deleted, model parameter estimates, and robust and non-robust estimates of the residual standard deviation"
        "x11regression|xot|t-statistics for every time point of each outlier detection iteration"
        "x11regression|xrm|values of irregular regression variables with associated dates"
        "x11regression|xrc|correlation matrix of irregular regression parameter estimates if used with the print argument; covariance matrix of same if used with the save argument"
    ];
    S = local_fill_spec_struct(S, lines);
end

function S = local_output_udg_description()
    lines = [ ...
        "acf|residual autocorrelations"
        "acf2|squared residual autocorrelations"
        "adjcori|composite series (prior adjusted)"
        "ador|original series (prior adjusted)"
        "ahst|concurrent and revised seasonal adjustments and revisions"
        "aichst|revision history of the likelihood statistics"
        "ao|regARIMA AO outlier component"
        "arat|final adjustment ratios"
        "armahst|ARMA model coefficient history"
        "bct|point backcasts and prediction intervals on the original scale"
        "btr|point backcasts and standard errors for the transformed data"
        "cad|regARIMA calendar adjusted original data"
        "caf|combined adjustment factors"
        "cal|combined calendar adjustment factors"
        "ccal|final combined calendar factors from irregular component regression"
        "cfchst|forecast and forecast error history"
        "chol|combined holiday component"
        "chss|sliding spans of the changes in the seasonally adjusted series"
        "cmpcad|regARIMA calendar adjusted composite data"
        "cmpoad|regARIMA outlier adjusted composite data"
        "cmpori|composite time series data (for the span analyzed)"
        "cmppadj|prior adjusted composite data"
        "cmpspor|spectrum of the composite series"
        "cmpsptukor|Tukey spectrum of the composite series"
        "csahst|history of the period-to-period changes of the seasonal adjustments"
        "ctd|final combined trading day factors from irregular component regression"
        "ctrhst|history of the period-to-period changes of the trend-cycle values"
        "fct|point forecasts and prediction intervals on the original scale"
        "fcthst|revision history of the out-of-sample forecasts"
        "fintst|final outlier test statistics"
        "fltsac|concurrent seasonal adjustment filter"
        "fltsaf|symmetric seasonal adjustment filter"
        "flttrnc|concurrent trend filter"
        "flttrnf|symmetric trend filter"
        "frfc|factors applied to get adjusted series with forced yearly totals"
        "ftr|point forecasts and standard errors for the transformed data"
        "idacf|residual autocorrelations for different orders of differencing"
        "idpacf|residual partial autocorrelations for different orders of differencing"
        "indahst|concurrent and revised indirect seasonal adjustments and revisions"
        "indao|indirect additive outlier adjustment factors"
        "indarat|indirect final adjustment ratios"
        "indcaf|indirect combined adjustment factors"
        "indcal|indirect calendar component"
        "indchss|sliding spans of the changes in the indirect seasonally adjusted series"
        "indfrfc|factors applied to get indirect adjusted series with forced yearly totals"
        "indirr|indirect irregular component"
        "indls|indirect level change adjustment factors"
        "indmirr|irregular component modified for extremes from indirect adjustment"
        "indmori|original data modified for extremes from indirect adjustment"
        "indmsa|seasonally adjusted data modified for extremes from indirect adjustment"
        "indrsi|final replacement values for SI component of indirect adjustment"
        "indsa|indirect seasonally adjusted data"
        "indsar|rounded indirect final seasonally adjusted series"
        "indsass|sliding spans of the indirect seasonally adjusted series"
        "indsat|final indirect seasonally adjusted series with forced yearly totals"
        "indsf|indirect seasonal component"
        "indsfss|sliding spans of the indirect seasonal factors"
        "indsi|indirect unmodified SI component"
        "indspir|spectrum of indirect modified irregular component"
        "indspsa|spectrum of differenced indirect seasonally adjusted series"
        "indsptukir|Tukey spectrum of indirect modified irregular component"
        "indsptuksa|Tukey spectrum of differenced indirect seasonally adjusted series"
        "indtadj|indirect total adjustment factors"
        "indtrn|indirect trend cycle"
        "indyyss|sliding spans of the year-to-year changes in the indirect seasonally adjusted series"
        "irr|final irregular component"
        "irrwt|final weights for irregular component"
        "ls|regARIMA level change outlier component"
        "mdlest|regression and ARMA parameter estimates"
        "mirr|modified irregular series"
        "mori|original data modified for extremes"
        "msa|modified seasonally adjusted series"
        "mvadj|original series adjusted for missing value regressors"
        "oad|regARIMA outlier adjusted original data"
        "ori|time series data (for the span analyzed)"
        "oricnt|time series data plus constant (for the span analyzed)"
        "orifctd|series forecast decomposition (SEATS)"
        "otl|regARIMA combined outlier component"
        "pacf|residual partial autocorrelation"
        "padj|prior-adjusted data"
        "padjt|prior-adjusted data (including prior trading day adjustments)"
        "ppradj|permanent prior-adjusted data"
        "ppradjt|permanent prior-adjusted data (including prior trading day adjustments)"
        "pprior|permanent prior-adjustment factors"
        "prior|prior-adjustment factors"
        "ptd|prior trading day factors"
        "regrsd|residuals from the estimated regression effects"
        "rgseas|regARIMA user-defined seasonal component"
        "rhol|regARIMA holiday component"
        "rsi|final replacement values for SI ratios"
        "rtd|regARIMA trading day component"
        "sa|final seasonally adjusted data"
        "sac|final seasonally adjusted series with constant value added"
        "safctd|final seasonally adjusted series forecast decomposition (SEATS)"
        "sar|rounded final seasonally adjusted series"
        "sass|sliding spans of the seasonally adjusted series"
        "sat|final seasonally adjusted series with forced yearly totals"
        "seataf|final combined adjustment factors (SEATS)"
        "seatase|standard error of final seasonally adjusted series (SEATS)"
        "seatcse|standard error of final transitory component (SEATS)"
        "seatcyc|final cycle"
        "seatdori|differenced original series after transformation, prior adjustment (SEATS)"
        "seatdsa|differenced final seasonally adjusted series (SEATS)"
        "seatdtr|differenced final trend (SEATS)"
        "seatirr|final irregular component (SEATS)"
        "seatltt|final long term trend"
        "seatsa|final seasonally adjusted series (SEATS)"
        "seatsf|final seasonal component (SEATS)"
        "seatsse|standard error of final seasonal component (SEATS)"
        "seatssm|sum of final seasonal component (SEATS)"
        "seattrn|final trend component (SEATS)"
        "seattse|standard error of final trend component (SEATS)"
        "setarat|final adjustment ratios (SEATS)"
        "setsac|final seasonally adjusted series with constant value added (SEATS)"
        "settadj|total adjustment factors (SEATS)"
        "settrc|final trend cycle with constant value added (SEATS)"
        "settrns|final transitory component (SEATS)"
        "sf|final seasonal factors"
        "sffctd|final seasonal component forecast decomposition (SEATS)"
        "sfhst|concurrent and projected seasonal component and their percent revisions"
        "sfr|seasonal factors, adjusted for user-defined seasonal regARIMA component"
        "sfss|sliding spans of the seasonal factors"
        "sgsac|squared gain of the concurrent seasonal adjustment filter"
        "sgsaf|squared gain of the symmetric seasonal adjustment filter"
        "sgtrnc|squared gain of the concurrent trend filter"
        "sgtrnf|squared gain of the symmetric trend filter"
        "si|final unmodified SI ratios"
        "siox|final unmodified SI ratios, with labels for outliers and extreme values"
        "so|regARIMA seasonal outlier component"
        "spcsir|spectrum of the irregular component (SEATS)"
        "spcssa|spectrum of the seasonally adjusted series (SEATS)"
        "spctuksir|Tukey spectrum of the irregular component (SEATS)"
        "spctukssa|Tukey spectrum of the seasonally adjusted series (SEATS)"
        "spexrsd|spectrum of the extended residuals (SEATS)"
        "spir|spectrum of modified irregular series"
        "spor|spectrum of the original series"
        "sprsd|spectrum of the regARIMA model residuals"
        "spsa|spectrum of differenced seasonally adjusted series"
        "sptukexrsd|Tukey spectrum of the extended residuals (SEATS)"
        "sptukir|Tukey spectrum of modified irregular series"
        "sptukor|Tukey spectrum of the original series"
        "sptukrsd|Tukey spectrum of the regARIMA model residuals"
        "sptuksa|Tukey spectrum of differenced seasonally adjusted series"
        "tadj|total adjustment factors"
        "tc|regARIMA temporary change outlier component"
        "tdhst|trading day coefficient history"
        "tdss|sliding spans of the trading day factors"
        "tprior|temporary prior-adjustment factors"
        "trancmp|regARIMA transitory component"
        "tranfcd|final transitory component forecast decomposition (SEATS)"
    ];
    S = local_fill_flat_struct(lines);
end

function S = local_fill_flat_struct(lines)
    S = struct();
    for i = 1:numel(lines)
        parts = split(lines(i), '|');
        key = matlab.lang.makeValidName(char(parts(1)));
        value = char(join(parts(2:end), '|'));
        S.(key) = value;
    end
end

function names = local_spec_names()
    names = {'arima','automdl','check','estimate','force','forecast','history', ...
        'metadata','identify','outlier','pickmdl','regression','seats','series', ...
        'slidingspans','spectrum','transform','x11','x11regression'};
end

function S = local_empty_spec_struct(specs)
    S = struct();
    for i = 1:numel(specs)
        S.(specs{i}) = struct();
    end
end

function S = local_empty_code_struct(specs)
    S = struct();
    for i = 1:numel(specs)
        S.(specs{i}) = {};
    end
end

function S = local_fill_spec_struct(S, lines)
    for i = 1:numel(lines)
        parts = split(lines(i), '|');
        spec = char(parts(1));
        key = matlab.lang.makeValidName(char(parts(2)));
        value = char(join(parts(3:end), '|'));
        S.(spec).(key) = value;
    end
end

function codes = local_codes(entries)
    if isempty(entries)
        codes = {};
        return
    end
    codes = cell(1, numel(entries));
    for i = 1:numel(entries)
        codes{i} = char(entries(i));
    end
end
