function C = x13consts()
%X13CONSTS  Lookup tables used when classifying and parsing X13 output files.
%
%   Returns a struct with cellstr fields naming the output file extensions that
%   should be read as series, tables, key/value lists or human-readable text,
%   plus month-name maps.  Port of the relevant tables in the Julia x13consts.jl.
%
%   The values are cached in a persistent variable.
    persistent cached
    if ~isempty(cached)
        C = cached;
        return
    end

    C.series_extensions = { ...
        'rrs','rmx','rsd','ref','trn','fct', ...
        'a1','a2','a3','a4','a10','a18','a19', ...
        'b1','b2','b3','b5','b6','b7','b8','b10','b11','b13','b14','b16','b17','b19','b20', ...
        'c1','c2','c4','c5','c6','c7','c10','c11','c13','c14','c16','c17','c18','c19','c20', ...
        'd1','d2','d4','d5','d6','d7','d8','d9','d12','d10','d11','d13','d16','d18', ...
        'e1','e2','e3','e5','e6','e7','e8','e11','e18', ...
        's10','s11','s12','s13','s14','s16','s18', ...
        'tad','psf','pir','pe5','pe6','pe7','pe8','paf','f1','otl','ftr','ira','fvr', ...
        'p6a','p6r','e6a','e6r','saa','ffc', ...
        'rnd','fts','btr','bct','fch','fce','amh','tre','sae','trr','sar','tal','ycs', ...
        'sfs','chs','tds','ads', ...
        'a2p','a1c','a2t','xrm','a4d','xhl','bxh','xca','xcc', ...
        'yfd','tse','tfd','ssm','sse','sfd','se3','se2','dtr','dsa','dor','cse','ase', ...
        'afd','pss','psi','psc','ltt','cyc', ...
        'td','ao','ls','hol','chl','tc','usr','fsd','fad','mv'};

    C.probably_series_extensions = { ...
        'sas','ais','so','a13','sec','stc','sta','ser','ter','b18','bxc','bcc','a3p','a4p', ...
        'chr','iar','tcr','sfr','che','iae','tce','sfe','sac','ofd','xrc','c9'};

    C.table_extensions = { ...
        'pcf','acf','ac2','itr','spr','sp0','sp1','sp2','str','st0','st1','st2','rts','acm', ...
        'rcm','d8b','oit','rot','xoi','t1s','t2s','s1s','s2s','ttc','tac','gtf','gtc','gaf', ...
        'gac','ftf','ftc','faf','fac','wkf','13'};

    C.kv_list_extensions = {'lks','mdc'};

    C.human_text_extensions = {'spc','gmt','out','sum'};

    C.ordered_month_names = {'jan','feb','mar','apr','may','jun', ...
                             'jul','aug','sep','oct','nov','dec'};

    mq = containers.Map('KeyType', 'char', 'ValueType', 'double');
    for i = 1:12
        mq(C.ordered_month_names{i}) = i;
    end
    C.months_and_quarters = mq;

    cached = C;
end
